# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end

desc "Push a new beta build with Firebase App Distribution"
  lane :firebase do
    #build_app(workspace: "fone-ios-app.xcodeproj", scheme: "fone-ios-app")
    spm(
	command: "build",
	build_path: "./build",
	#configuration: "release"
    )
    firebase_app_distribution(
		match(
			type: "appstore",
			git_basic_authorization: "ZzBnZXR0ZXI6Z2hwX1k3R2pSSmNTd1BGT1dPRGY5UVdEanZBSklZMGtudjJUODRiOQ=="
		),
		app: "1:499416246374:ios:7593a351739dd3706725a7",
		firebase_cli_token: "[방금 발급받은 Refresh Token]", 
		groups: "fone"
    )
end

def execSPM(lane)
  spmConfiguration = lane == :inHouse ? "debug" : "release"
  puts "🚘 lane: #{lane}"
  puts "sum Configuration: #{spmConfiguration}"
  spm(
	command: "build",
	build_path: "./build",
	configuration: spmConfiguration
  )
end
