name: App Store

on:
  pull_request:
  

jobs:
  appstore:
    runs-on: macos-latest
    strategy:
          matrix:
            node: [ '12', '14' ]
            ruby: [ '2.6' ]

    steps:
      - uses: actions/checkout@v2

      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}          
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - run: brew install fastlane

      - run: fastlane upload 
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}